### ISSUE TITLE
Error when running biosample transform

### ISSUE THREAD

**Issue by prismofeverything** [biostream/gdc-transform#6]
Looks like the schema is missing the barcode property? 

                     Traceback (most recent call last):
                       File "/opt/convert-clinical.py", line 525, in <module>
                         process_input(state, tmpdir, process_file)
                       File "/opt/convert-clinical.py", line 72, in process_input
                         process_input(state, elem, process)
                       File "/opt/convert-clinical.py", line 75, in process_input
                         state = process(state, input)
                       File "/opt/convert-clinical.py", line 492, in process_file
                         return extract.parseXMLFile(state, dom)
                       File "/opt/convert-clinical.py", line 371, in parseXMLFile
                         self.emit( state, sample_barcode, sample_data, "Biosample" )
                       File "/opt/convert-clinical.py", line 454, in emit
                         state['generators'][entry_type].find(entry)
                       File "/opt/convert-clinical.py", line 153, in find
                         record = self.create(data)
                       File "/opt/convert-clinical.py", line 146, in create
                         self.update(record, data)
                       File "/opt/convert-clinical.py", line 219, in update
                         sample.barcode = data['bcr_sample_barcode']
                     AttributeError: Assignment not allowed (no field "barcode" in protocol message object).

**Comment by kellrott** [comment]
should probably be `name` rather then `barcode`

**Comment by kellrott** [comment]
Fixed in https://github.com/biostream/gdc-transform/commit/7a2c6763685d3f6031aa8bbad8a156ee5b0c4190
